# Generated by Django 5.1.1 on 2025-01-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hairstyle", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceimage",
            options={"ordering": ["order"]},
        ),
    ]
