# Generated by Django 5.1.1 on 2025-02-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_barber"),
        ("hairstyle", "0003_reviewimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="barber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Appointments",
                to="account.barber",
            ),
        ),
    ]
