# Generated by Django 5.1.1 on 2025-02-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_barber_pfp_alter_specialist_barber_shop"),
        ("hairstyle", "0004_appointment_barber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="barber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Appointments",
                to="account.barber",
            ),
        ),
    ]
