# Generated by Django 5.1.1 on 2025-03-16 11:48

import hairstyle.models.appointment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hairstyle", "0005_alter_appointment_barber"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="unread_messages",
            field=models.JSONField(
                default=hairstyle.models.appointment.get_default_unread_messages
            ),
        ),
    ]
