# Generated by Django 5.1.1 on 2025-05-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hairstyle", "0008_create_message_threads_for_existing_appointments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="unread_messages",
        ),
        migrations.AlterField(
            model_name="appointmentmessagethread",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_thread",
                to="hairstyle.appointment",
            ),
        ),
    ]
