# Generated by Django 5.1.1 on 2025-05-24 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle', '0009_remove_appointment_unread_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hairstyle.appointment'),
        ),
    ]
