# Generated by Django 5.1.1 on 2025-01-20 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rewardpoints_dayavailability"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Holiday"),
                            (1, "Vacation"),
                            (2, "Sick Leave"),
                            (3, "Personal"),
                            (4, "Other"),
                        ],
                        help_text="Type of day off",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the day off")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this day off was recorded"
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        help_text="The specialist taking the day off",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days_off",
                        to="account.specialist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Day Off",
                "verbose_name_plural": "Days Off",
                "ordering": ["-date"],
            },
        ),
    ]
