# Generated by Django 5.1.1 on 2025-01-20 13:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_dayoff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rewardpoints",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Reward Points",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="rewardpoints",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rewardpoints",
            name="points",
            field=models.IntegerField(
                help_text="Number of points awarded (minimum 1)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="point_to_php",
            field=models.FloatField(
                default=0.0,
                help_text="Conversion rate from points to PHP currency",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="dayoff",
            constraint=models.UniqueConstraint(
                fields=("specialist", "date"), name="unique_specialist_day_off"
            ),
        ),
    ]
