# Generated by Django 5.1.1 on 2025-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_rewardpoints_options_customer_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialist",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Specialist's biography and description",
                null=True,
            ),
        ),
    ]
