# Generated by Django 5.1.1 on 2025-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_specialist_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="google_maps_link",
            field=models.URLField(
                blank=True,
                help_text="Google Maps link for the specialist's location",
                null=True,
            ),
        ),
    ]
