# Generated by Django 5.1.1 on 2025-02-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_specialist_google_maps_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarberShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the barber shop", max_length=255
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="specialist",
            name="barber_shop",
            field=models.OneToOneField(
                blank=True,
                help_text="If user type is a barber shop",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialists",
                to="account.barbershop",
            ),
        ),
    ]
