# Generated by Django 5.1.1 on 2025-02-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_alter_barber_pfp"),
        ("general", "0002_remove_file_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="pfp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="barber_pfps",
                to="general.file",
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="barber_shop",
            field=models.OneToOneField(
                blank=True,
                help_text="If user type is a barber shop",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specialists",
                to="account.barbershop",
            ),
        ),
    ]
