# Generated by Django 5.1.1 on 2025-02-13 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_barber_pfp_alter_specialist_barber_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Time when the appointment slot starts"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="Time when the appointment slot ends"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this time slot is available for booking",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this time slot was created"
                    ),
                ),
                (
                    "day_availability",
                    models.ForeignKey(
                        help_text="The day availability this time slot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="account.dayavailability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Time Slot",
                "verbose_name_plural": "Appointment Time Slots",
                "ordering": ["start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_time__lt", models.F("end_time"))),
                        name="appointment_start_before_end",
                    ),
                    models.UniqueConstraint(
                        fields=("day_availability", "start_time", "end_time"),
                        name="unique_time_slot",
                    ),
                ],
            },
        ),
    ]
