# Generated by Django 5.1.1 on 2025-02-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_appointmenttimeslot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
    ]
