# Generated by Django 5.1.1 on 2025-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="auto_accept_appointment",
            field=models.BooleanField(
                default=False,
                help_text="If the specialist should automatically accept appointments",
            ),
        ),
    ]
