# Generated by Django 5.1.1 on 2025-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_qnaquestion_qnaanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
