# Generated by Django 5.1.1 on 2025-03-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmenttimeslot",
            name="is_available",
        ),
    ]
