# Generated by Django 5.1.1 on 2025-03-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_remove_appointmenttimeslot_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmenttimeslot",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Whether this time slot is available for booking",
            ),
        ),
    ]
