# Generated by Django 5.1.1 on 2025-03-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_appointmenttimeslot_is_available"),
        ("general", "0002_remove_file_removed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistShopImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_shop_images",
                        to="general.file",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_images",
                        to="account.specialist",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("specialist", "order"),
                        name="unique_specialist_shop_image_order",
                    )
                ],
            },
        ),
    ]
