# Generated by Django 5.1.1 on 2025-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_specialistshopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorite_specialists',
            field=models.ManyToManyField(blank=True, help_text='Specialists marked as favorite by this customer', related_name='favorited_by', to='account.specialist'),
        ),
    ]
