# Generated by Django 5.1.1 on 2025-03-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_specialistshopimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Full address of the specialist's shop location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialist",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Latitude coordinate of the specialist's shop location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialist",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Longitude coordinate of the specialist's shop location",
                null=True,
            ),
        ),
    ]
