# Generated by Django 5.1.1 on 2025-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_customer_favorite_specialists"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="specialist",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Full address of the specialist's location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialist",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Latitude coordinate of the specialist's location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="specialist",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Longitude coordinate of the specialist's location",
                null=True,
            ),
        ),
    ]
