# Generated by Django 5.1.1 on 2025-05-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_usernotification_is_read_alter_usernotification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="redirect_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("appointment", "Appointment"),
                    ("message", "Message"),
                    ("review", "Review"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
